stages:
  - update
  - test

update_contentDB:
  stage: update
  tags:
    - nix
  script:
    - git checkout -B "$CI_COMMIT_BRANCH"
    - nix run --extra-experimental-features "nix-command flakes pipe-operators" .\#fetchContentDB
    - git config --global user.email "ci-pipeline@menzel.lol"
    - git config --global user.name "CI Pipeline"
    - git add *
    - git commit -m "update ContentDB" || echo "No changes to commit"
    - git remote set-url origin "https://leonard:$GITLAB_TOKEN@git.menzel.lol/$CI_PROJECT_PATH.git"
    - git push origin "$CI_COMMIT_BRANCH"

build_test_pipeline:
  stage: test
  tags:
    - nix
  script:
    - nix build --extra-experimental-features "nix-command flakes pipe-operators" .\#testPipeline
    - cat result > test_pipeline.yml
  artifacts:
    paths:
      - test_pipeline.yml

trigger_test_pipeline:
  stage: test
  dependencies:
    - build_test_pipeline
  trigger:
    include:
      - artifact: test_pipeline.yml
        job: build_test_pipeline
    strategy: depend