stages:
  - update
  - test
update_contentDB:
  stage: update
  tags:
    - nix
  script:
    - git checkout -B "$CI_COMMIT_BRANCH"
    - git config --global user.email "ci-pipeline@menzel.lol"
    - git config --global user.name "CI Pipeline"
    - nix flake update --extra-experimental-features "nix-command flakes pipe-operators"
    - nix run --extra-experimental-features "nix-command flakes pipe-operators" .\#fetchContentDB
    - git add *
    - nix fmt --extra-experimental-features "nix-command flakes pipe-operators"
    - git add *
    - git commit -m "update and format" || echo "no changes to commit"
    - nix flake check --extra-experimental-features "nix-command flakes pipe-operators"
    - git remote set-url origin "https://leonard:$GITLAB_TOKEN@git.menzel.lol/$CI_PROJECT_PATH.git"
    - git push origin "$CI_COMMIT_BRANCH"
    - echo "updates pushed"

test:
  tags:
    - nix
  stage: test
  script:
    - nix flake check --extra-experimental-features "nix-command flakes pipe-operators"
